package com.girrafeecstud.example_connections_list.connections_impl.util

internal object ConnectionsFeatureUtils {

    const val CONNECTIONS_WITH_DISTANCE_SERVICE_MODE = "CONNECTIONS_WITH_DISTANCE_SERVICE_MODE"

    const val CONNECTIONS_WITH_DISTANCE_TO_USER_MODE = "CONNECTIONS_WITH_DISTANCE_TO_USER_MODE"

    const val CONNECTIONS_WITH_DISTANCE_TO_CHOSEN_CONNECTION_MODE = "CONNECTIONS_WITH_DISTANCE_TO_CHOSEN_CONNECTION_MODE"

    const val CHOSEN_CONNECTION = "CHOSEN_CONNECTION"
}