package com.girrafeecstud.example_connections_list.connections_list.navigation

import com.girrafeecstud.navigation_api.INavigationDestination

sealed class ConnectionsListDestination : INavigationDestination